[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "scraper.tmpl"

# The location to place the rendered configuration file
dest = "/var/www/html/apps.html"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ "/maestro.io/apps", "/skydns/io/maestro" ]

# File ownership and mode information
owner = "root"
mode = "0644"
